# Generated by Django 4.0.1 on 2022-01-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
